### ISSUE TITLE
[question] Your "rebuild" phonitor

### ISSUE THREAD

**Issue by Ebert-Hanke** [mnaganov/mnaganov.github.io#1]
While doing research about Crossfeed I have found your great post about rebuilding the Phonitor. It was very interesting to read and the measurements and the work you put into it are impressive!
I have started to work on a little tool to combine [AutoEq](https://github.com/jaakkopasanen/AutoEq) with Crossfeed to use in [CamillaDSP](https://github.com/HEnquist/camilladsp) and would like to include more DSP crossfeed implementations in the future. If it is ok I would like to base one on your findings or maybe you feel like designing one for CamillaDSP yourself.
This ist my little project:
https://github.com/Ebert-Hanke/autoeq2camilladsp

**Comment by mnaganov** [comment]
Hi Ebert-Hanke, thanks for your question! The CamillaDSP project looks interesting. For my projects these days I usually just use commercial (or freeware) plugins running in Reaper DAW, but I was always wondering about a more portable and headless solution.

Yes, sure, you can try build something based on my measurements. Currently I use RedLine Monitor plugin instead of a physical Phonitor because I apply cross-feed before equalization. I did some comparison between RedLine and Phonitor crossfeed implementations here: https://mnaganov.github.io/2018/02/112db-redline-monitor-plugin.html.

I'll take a look into your project too, but please don't wait on me :)

**Comment by Ebert-Hanke** [comment]
Hi Mikhail, thank you for the fast reply! Its great that I can take your measurements as a starting point! I will put some background information and your credit and blogpost with it in the Readme.

From my understanding the signal chain would be like this:

```mermaid
graph LR
A[Left IN]-- -2.3 dB --> G[Highshelf Filter 200 Hz +2.3 dB]--> B[Left OUT]
A -- -9.9 dB --> E[Highshelf Filter 750 Hz -0.3 dB] --> I[Peaking EQ 180 Hz +0.5 dB Q 0.55] --> D
C[Right IN]-- -2.3 db -->H[Highshelf Filter 200 Hz +2.3 dB]-->D[Right OUT]
C -- -9.9 dB --> F[Highshelf Filter 750 Hz -0.3 dB] --> J[Peaking EQ 180 Hz +0.5 dB Q 0.55] -->B
```
What I still do not really grasp is the whole topic of delay in crossfeed which should be relevent for the psychoaccustic effect and it does show up in your measurements. But where does it come from? If I understand the implementation of `bs2b` correctly there is an actual delay in the DSP signal chain ...

Thank you and best regards
micha

**Comment by mnaganov** [comment]
Hi again Micha! Apologies, the last time I didn't realize that your GH name is actually your last name :)

Agree, delays are an interesting topic. First of all, I would like to correct you that the delays in the crossfeed simulation simulate purely physical phenomena—the fact that sound waves need some time in order to reach the opposite ear after they have reached the "direct" ear. Whereas "psychoacoustic" effects are those that occur due to how human perceptual system works. Examples of psychoacoustic effects are the precedence effect (https://en.wikipedia.org/wiki/Precedence_effect) and masking effect (https://en.wikipedia.org/wiki/Auditory_masking).

And in fact the delays come naturally from the filters implementation. Since we use "minimum phase" filters, besides the modifications of the amplitude they also modify the phase of the processed signal. Modifications of the phase affect relative timings of frequencies. This is usually referred to as "group delay." This is explained in every book on DSP, but usually involves a lot of math. Instead, you can easily play with it using RoomEq Wizard (REW), there is even no need to make any actual measurements, this is how.

If you start with blank REW, you still can open the "EQ" dialog (Tools > EQ), there press the "EQ filters" button and add necessary filters with "Manual" type of control. High shelf filters are abbreviated as "HS" and peaking EQ as "PK." Once you select them, you will see familiar parameters that you need to specify. Now you can export these filters as a "measurement" for further analysis. To do that, make sure that the type of the equalizer is set to "miniDSP" or "Generic", then expand "Filter tasks" section and select "Generate measurement from filters." Then use the "SPL & Phase" tab to check the phase changes caused by the filter, and the "GD" tab to check the resulting group delay. Note that you will need to zoom in vertically a lot since the resulting group delays are in microseconds.

Note that the actual phase changes and group delays will still depend on the implementation of the filter, so you will want to actually measure its transfer function.

**Comment by Ebert-Hanke** [comment]
Hi Mikhail, 
oh no worries about the name, always hard to tell. 
And thank you for the correction, you are of course right. Classic example of me assuming to know what something might mean without proper checking (...) I guess what I meant was the fact that the delayed crossfeed signal tricks our brains into believing it is actual spacial information. 

Thank you so much for taking the time to explain the group delay to me! This is amazing. I went along and tested in REW. I should also read up on DSP but most likely this is beyond my mathmatical abilities to understand. The detailed walk through in REW was therefore extremely helpful. I understand a lot better now. There is so many people in forums who put actual delay filters in their chains and when I tested it mostly sounded off to me.

Following your instructions i compared the crossfeed I am using now (modelled after Pow Chu Moy) to your signal chain and there is quite a difference in the group delay which is interesting.  

I recently experimented with Mid/Side and played with an effect which was mentioned in some mastering tutorial on YT. If you havent looked into it might be worth to give it a listen. 
If one introduces very minimal phase shift in a M/S chain it creates a very spacial sound effect. I would call it more deep than wide and I personally dont find it too pleasant in terms of music listening but it is still quite substantial.
In Reaper for example it is easy to do with the M/S encoder and decoder. In between you could either delay one channel (M or S create different effects) very minimal to introduce phase shift (something like 0.03 ms) or use an All Pass EQ filter which introduces a much stronger phase shift. I am not sure if I will put this as a possible conifguration but could imagine someone might like the effect. In general I think there must be potential for crossfeed like effects with M/S but so far my experiments did not really satisfy me. I think it is because of the fact that everything in the Side-Channel is also always present in the Mid-Channel. It can easily be reproduced in CamillaDSP as well.

I will add the config for your "Rebuild Phonitor" the next days and maybe also this M/S effect as an option. I would just call it "Mnaganov Crossfeed" (?) or would you prefer something else? (I think phonitor might be a trademark.)

Thanks for sharing so much helpful information and insight about the topic!

**Comment by mnaganov** [comment]
Micha, that's a very interesting discussion! Yes, the M/S technique is well known, for example see https://www.soundonsound.com/techniques/classic-stereo-widening. However, it's not related to crossfeed at all :)

The intent of use of a crossfeed is to go from what's called "dichotic" listening in headphones—when each ear receives independent audio streams—to "binaural" which attempts to emulate what happens when we are listening to a stereo speaker setup. And the intent is at least to "get sound of your head," if not trick your brain completely that it is actually listening to external sound sources (similar to VR). In fact, just feeding L ear with L+R audio and vice versa unfortunately is not enough for that. Have you seen this post of mine where I describe the processing chain that I'm currently using and which I'm still evolving?— https://mnaganov.github.io/2021/11/headphone-stereo-setup.html. The tricky part is finding the right balance between the amount of processing which inevitably changes the sound, and the achieved "out of your head" effect. For example, if you don't mind buying a plugin and a piece of hardware, you can try WavesNx: https://www.waves.com/hardware/nx-virtual-mix-room-nx-head-tracker. Although it indeed works for externalizing the audio, I don't find the result sounding natural to me. Although, we might see better technologies later with Apple and Dolby being in the game. I actually like how Atmos tracks sound in Apple Music, but unfortunately this only works for albums mastered for Atmos.

For the name of my EQ curves—I don't know really—perhaps call it "German Crossfeed" (as SPL is a German company)? I don't think it's fair to call it using my name as I simply reverse engineered (and maybe not even very good) what SPL did.

**Comment by Ebert-Hanke** [comment]
Hi Mikhail, ah yes true, it is not crossfeed. I meant in the sense of creating a more open / wide experience while listening with headphones. 

> Have you seen this post of mine where I describe the processing chain that I'm currently using and which I'm still evolving?— https://mnaganov.github.io/2021/11/headphone-stereo-setup.html. 

I just read it :) Very cool setup with lots of stuff going into it! Seems like you are really on a journey striving for the ultimate headphone experience, very inspiring!

I personally always liked headphone listening partly because of its "unnatural" sound characteristics. But I like crossfeed since it takes away the problem of listening fatigue (at least for me). In this regard I really like what you came up with in terms of "reverse engineering" on your blog. This setup to me sounds very nice and enjoyable and kind of hits the sweet spot. Therefore I really wanted to include it as a preset.

The Atmos thing Apple is doing in Apple Music so far has not convinced me to be honest. Maybe it is just not my taste in headfi. Possibly it is just because the music I listen to is not properly (re)mastered to the format. I guess I still want headphones to be a very different experience than speakers in general but that being said it should of course be plesant to listen to ... and that obviously is just very personal and a matter of preference where each person must seek their own thing. I guess thats the fun in highfi in the end :)

I did include the new preset and called it `MMP Crossfeed` for the moment ... pobably ambigue enough. Since I will also include a Crossfeed based on Meier's implementation in the future there would have been two "german crossfeeds" then. 
I also updated the readme with some credits and there is a pre-release available. If you have any changes for this, please let me know. 

https://github.com/Ebert-Hanke/autoeq2camilladsp/tree/develop

**Comment by mnaganov** [comment]
Thanks for your endorsements, Micha! The page looks good, I would just ask you to fix my last name to "Naganov", because "mnaganov" is in fact my usual account name resulting from concatenating the first letter of the name with the last name :)

It's interesting to learn about your point of view on the headphone listening experience! That's why I love to talk to different people, because it's easy too get locked into your own view of things.

**Comment by Ebert-Hanke** [comment]
Mikhail, I am very sorry ... I actually have a friend whos name is starting with "mn" so I guess I did not question it. It is corrected now and the crossfeed called "MPM Crossfeed" for something like Mikhail's Phonitor Mini ;)

And yes it is always very enjoyable to discuss these topics with other people. Thanks again for all your input :) I have learned a lot (also from your blog)!
